### ISSUE TITLE
Add ModelMesh documentation to website

### ISSUE THREAD

**Issue by pvaneck** [kserve/website#17]
Some information about ModelMesh should be added to the KServe website. Can probably make a modelmesh folder [here](https://github.com/kserve/website/tree/main/docs/modelserving) for now with a few md files. 

Need to later determine if we can use the docs located https://github.com/kserve/modelmesh-serving/tree/main/docs as the main source of the modelmesh docs without having to duplicate a lot of the docs in both places. Or if mkdocs even supports that. Otherwise, we can just keep a subset of the docs on the website.

FYI @animeshsingh

**Comment by chinhuang007** [comment]
For the immediate release v0.7.0, the general approach is to leave ModelMesh docs in modelmesh-serving repo, without moving them to the website.

We will look into moving ModelMesh docs to the website post v0.7.0
