### ISSUE TITLE
"Build the custom image with Buildpacks" section needs more info.

### ISSUE THREAD

**Issue by thoo** [kserve/website#180]
**Describe the change you'd like to see**
**[Build the custom image with Buildpacks](https://kserve.github.io/website/0.9/modelserving/v1beta1/custom/custom_model/#build-the-custom-image-with-buildpacks)** might need to update. Currently `pack build --builder=heroku/buildpacks:20 ${DOCKER_USER}/custom-model:v1`  won't work without specifying the correct `python version` at `runtime.txt`. `heroku/buildpacks:20` comes with `python-3.10` but `ray[serve]=1.10.0 , kserve=0.9.0` requires `python-3.9`. 

**Additional context**
The additional file `runtime.txt` file with `python-3.9.13` is required to successfully build a docker image for a custom model serving.

**Comment by alexagriffith** [comment]
good catch. made PR to clarify https://github.com/kserve/website/pull/203
