### ISSUE TITLE
Update repo_url for the website

### ISSUE THREAD

**Issue by peterableda** [kserve/website#244]
## Expected Behavior
The docs should link to the https://github.com/kserve/kserve GitHub repo instead of https://github.com/kserve/website. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4995445/230767911-bc39dd46-7bee-4825-995e-de36714c0655.png">

The aesthetics on this is quite bad, at first glance, all pages of the kserve documentation tell me that the kserve project has 72 stars and 65 forks. Also, most users would want to visit the main repository of the project instead of the repo for the documentation.

**Comment by yuzisun** [comment]
We are following what knative does https://knative.dev/docs/serving, but good point we can either refer to the main repo or we need to get more stars for the website repo :)
