### ISSUE TITLE
Update docs with better formatting for v2 protocol page

### ISSUE THREAD

**Issue by andyi2it** [kserve/website#258]
We should do something very similar to https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html ? as far as the formatting goes.

We should replace the hardcoded table in the v2_protocol page https://kserve.github.io/website/master/modelserving/data_plane/v2_protocol/

Thanks @alexagriffith for the suggestions

**Comment by alexagriffith** [comment]
👍
