### ISSUE TITLE
Latest changes to main are not being deployed to website/gh-pages

### ISSUE THREAD

**Issue by paravatha** [kserve/website#302]
## Expected Behavior
When we merge a PR to `main` branch, the changes should show up on https://kserve.github.io/website

## Actual Behavior
- The PRs merged to `main` branch in the last 2 months are not showing up on the docs site
- https://kserve.github.io/website redirects to https://kserve.github.io/website/0.11/
- it looks like the default branch is set to [v0.11](https://github.com/kserve/website/tree/v0.11) under [git pages setting ](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) for this repo

## Steps to Reproduce the Problem
For example, below approved PRs are not reflecting on the website 
1. https://github.com/kserve/website/pull/300
1. https://github.com/kserve/website/pull/299

## Additional Info
**Possible solution** 

_**Someone with permissions need to check the pages settings and update it to `main` branch if required**_

**Comment by paravatha** [comment]
@yuzisun @theofpa if you are admins/maintainers for this repo, can you please take a look at this issue?

**Comment by yuzisun** [comment]
It should be published now
