### ISSUE TITLE
Unable to run inference service

### ISSUE THREAD

**Issue by VikasAbhishek** [kserve/website#355]
I have followed the official documentation and deployed the serverless deployment, but after running the first inference service example. I am unable to get desired result that has shown in the page. Please find attached image here with

I followed this link for running the inference service 
https://kserve.github.io/website/master/get_started/first_isvc/#5-perform-inference

<img width="761" alt="Screenshot 2024-04-01 185643" src="https://github.com/kserve/website/assets/165130322/238e8e6e-538f-48a4-8d44-6a923091f3fd">

**Comment by spolti** [comment]
Hi @VikasAbhishek, what the command below returns?
```bash
kubectl get isvc
```

**Comment by VikasAbhishek** [comment]
Classification: Confidential
Hi Filippe,
Please find attached image.

**Comment by spolti** [comment]
there is nothing attached, just pasting the text here should be enough,.

**Comment by VikasAbhishek** [comment]
Classification: Confidential
***@***.***:/home/ubuntu# kubectl get isvc -n kserve-test
NAME           URL                                                 READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION            AGE
sklearn-iris   http://sklearn-iris.kserve-test.svc.cluster.local<http://sklearn-iris.kserve-test.svc.cluster.local/>   True           100                              sklearn-iris-predictor-00003   5d6h

**Comment by sivanantha321** [comment]
@VikasAbhishek Seems like you have not configured a domain or DNS. If you try to infer from outside the cluster it won't work

**Comment by VikasAbhishek** [comment]
Classification: Confidential
Hi Sivanantham,
Can you please guide me how to configure DNS and in which services should I make the changes. If you have any example file for the same, please share with me.

Thank you,
Vikas Ghunawat Meena

**Comment by sivanantha321** [comment]
Here is the docs from [knative for configuring domain](https://knative.dev/docs/serving/using-a-custom-domain/). If you are just doing it for testing purposes, then you can just use this command below and you can use the kubectl port-forward to access the cluster without the need to configuring DNS.
```bash
kubectl patch cm config-domain --patch '{"data":{"example.com":""}}' -n knative-serving
```
If you want to [configure DNS follow this doc](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns)

**Comment by VikasAbhishek** [comment]
Classification: Confidential
***@***.***:/home/ubuntu# kubectl logs load-testf4ps9-qznqs -n kserve-test
Requests      [total, rate, throughput]         30000, 500.02, 0.00
Duration      [total, attack, wait]             59.999s, 59.998s, 663.663µs
Latencies     [min, mean, 50, 90, 95, 99, max]  427.534µs, 790.51µs, 748.113µs, 955.089µs, 1.052ms, 1.593ms, 26.421ms
Bytes In      [total, mean]                     0, 0.00
Bytes Out     [total, mean]                     2460000, 82.00
Success       [ratio]                           0.00%
Status Codes  [code:count]                      404:30000
Error Set:
404 Not Found

I am getting these logs while running the performance test.

**Comment by VikasAbhishek** [comment]
Classification: Confidential
***@***.***:/home/ubuntu# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict<http://$%7bINGRESS_HOST%7d:$%7bINGRESS_PORT%7d/v1/models/sklearn-iris:predict> -d @./iris-input.json
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.kserve-test.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 76
>
* upload completely sent off: 76 out of 76 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Thu, 04 Apr 2024 13:15:37 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 3
< content-length: 0
<
* Connection #0 to host localhost left intact

I am still getting the same issue.

**Comment by Syntax-Error-1337** [comment]
@VikasAbhishek 
- Ensure the KServe inference service (sklearn-iris) is correctly deployed and accessible within the Kubernetes cluster. The command kubectl get isvc -n kserve-test should list the service as READY.
- Ensure the ingress setup and network policies allow external traffic to the service. The persistent 404 errors could indicate network misconfiguration or an incorrect URL.
- lacking a proper DNS configuration could prevent external access. Using ```kubectl patch cm config-domain --patch '{"data":{"example.com":""}}' -n knative-serving``` can set a temporary domain for testing purposes.

**Comment by VikasAbhishek** [comment]
Resolved.
