### ISSUE TITLE
Website rendering error

### ISSUE THREAD

**Issue by nimishamehta5** [kserve/website#411]
The webpage for Getting started > First InferenceService seems to be broken: https://kserve.github.io/website/master/get_started/first_isvc/

## Expected Behavior
This webpage should load and not have a rendering error.

## Actual Behavior

<img width="893" alt="Screenshot 2024-10-22 at 8 58 49 PM" src="https://github.com/user-attachments/assets/8cd25b46-9304-4c1e-9c9c-dc3dd61aab75">

## Steps to Reproduce the Problem

1. Visit https://kserve.github.io/website/master/get_started/first_isvc/.

**Comment by spolti** [comment]
Thanks for reporting.

**Comment by spolti** [comment]
Fixed by https://github.com/kserve/website/pull/410
